### ISSUE TITLE
Missing R package genomation

### ISSUE THREAD

**Issue by JihedC** [ftabaro/rrbs-pipeline#7]
Hi,
The pipeline worked fine until the rule `run_methylkit_analysis` where I got this:
```
[Fri Feb  5 08:19:44 2021]
Job 0: Performing methylKit analysis...

Rscript /exports/humgen/jihed/rrbs_zbtb24/MethylSnake/MethylSnake-1.1.1/.snakemake/scripts/tmpc5gro0mj.methylkit_analysis.R
#################################
## Starting methylKit analysis ##
#################################
Error in library(genomation) : there is no package called ‘genomation’
Calls: suppressPackageStartupMessages -> withCallingHandlers -> library
Execution halted
[Fri Feb  5 08:20:06 2021]
Error in rule run_methylkit_analysis:
    jobid: 0
    output: /exports/humgen/jihed/rrbs_zbtb24/MethylSnake/MethylSnake-1.1.1/log/methylkit_analysis0.01_15.0.done
```

Genomation package is missing. I am installing it at the moment.

Best regards,

Jihed

**Comment by ftabaro** [comment]
If you're using Singularity, you will need to rebuild the containers! I will upload an updated version to Singularity library later.

**Comment by JihedC** [comment]
Sorry I didn't use singularity much. When you say rebuild the containers, I need to redo : 
`singularity pull library://ftabaro/default/methylsnake` ?

**Comment by ftabaro** [comment]
I have uploaded a new version of the Singularity container to the library. Please, update yours by pulling the new version.

**Comment by JihedC** [comment]
Thanks it works now
